name: Scrape coinMarketCap

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: AWS Credientials
    steps:
      - uses: actions/checkout@v2
      - name: Create credentials folder
        run: mkdir src/credentials
      - uses: gr2m/write-csv-file-action@v1.x
        with:
          path: src/credentials/local-dynamoDB-access_accessKeys.csv
          columns: Access key ID,Secret access key
          "Access key ID": ${{ secrets.ACCESS_KEY_ID }}
          "Secret access key": ${{ secrets.SECRET_ACCESS_KEY }}
      - name: Build Docker Image
        run: docker compose build
      - name: Scrape 
        run: docker compose up --exit-code-from app   
