name: Scrape Threads

on:
  workflow_dispatch:
  schedule:
    - cron: "15 8 * * *"

jobs:
  Scrape:
    runs-on: ubuntu-latest
    environment: Credentials
    steps:
      - uses: actions/checkout@v2

      - name: Create credentials folder
        run: mkdir src/credentials

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Start up Standalone-Chrome docker container
        run: 
          docker pull selenium/standalone-chrome:latest
          docker run -d -p 4444:4444 -p 5900:5900 --shm-size="2g" selenium/standalone-chrome:latest

      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10.4'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Setup Environment Variables
        run: 
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> "$GITHUB_ENV"
          echo "AWS_PROFILE=${{ secrets.AWS_ROLE_TO_ASSUME }}" >> "$GITHUB_ENV"
          echo "AWS_DYNAMODB_TABLE=webscraper-threads-posts-table" >> "$GITHUB_ENV"
          echo "THREADS_LOGIN_URL=https://www.threads.net/login" >> "$GITHUB_ENV"
          echo "THREADS_LOGIN_USERNAME=${{ secrets.THREADS_LOGIN_USERNAME }}" >> "$GITHUB_ENV"
          echo "THREADS_LOGIN_PASSWORD=${{ secrets.THREADS_LOGIN_PASSWORD }}" >> "$GITHUB_ENV"
          echo "THREADS_URL=https://www.threads.net/search?q=cryptocurrency" >> "$GITHUB_ENV"
          echo "THREADS_POSTS_LIMIT=100" >> "$GITHUB_ENV"
          echo "TIMEZONE=Asia/Hong_Kong" >> "$GITHUB_ENV"
      - name: Scrape Threads
        run: python src/threads_webscraper.py

      - name: Stop Standalone-Chrome docker container
        run: docker stop $(docker ps -q) 
